[tool.poetry]
name = "pygui"
version = "0.1.0"
description = "Reactive rendering for Python"
authors = ["Korijn van Golen <korijn@gmail.com>", "Berend Klein Haneveld <berendkleinhaneveld@gmail.com>"]
license = "MIT"
homepage = "https://github.com/fork-tongue/pygui"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
# NOTE: When observ is updated, the python marker can be removed
observ = { version = "~0.9.0", python = "<3.11" }
pygfx = { git = "https://github.com/pygfx/pygfx.git", rev = "main" }
PySide6 = { version = "*", python = "<3.11" }

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
flake8-black = "*"
flake8-import-order = "*"
flake8-print = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
twine = "*"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
